- name: Docker container deploy
  hosts: web
  become: yes

  tasks:

    - name: Docker ve Docker Compose kur
      apt:
        name: 
          - docker.io
          - docker-compose
        state: present
        update_cache: yes

    - name: Docker başlat
      service:
        name: docker
        state: started
        enabled: yes

    - name: Hedef klasörü oluştur
      file:
        path: /opt/mhrs
        state: directory

    - name: Docker Compose dosyasını oluştur (Template)
      template:
        src: "{{ playbook_dir }}/../docker-compose.yml.j2"
        dest: /opt/mhrs/docker-compose.yml

    - name: Docker Hub login
      shell: echo "{{ docker_pass }}" | docker login -u "{{ docker_user }}" --password-stdin
      when: docker_pass is defined

    - name: Yeni imajları çek
      shell: docker compose pull
      args:
        chdir: /opt/mhrs

    - name: Eski containerları durdur ve kaldır
      shell: docker compose down
      args:
        chdir: /opt/mhrs
      ignore_errors: yes

    - name: Docker Compose ile uygulamayı ayağa kaldır
      shell: docker compose up -d
      args:
        chdir: /opt/mhrs
