name: CI-CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:

    - name: Repo çek
      uses: actions/checkout@v3

    - name: Docker login
      run: echo "${{ secrets.DOCKER_PASS }}" | docker login -u "${{ secrets.DOCKER_USER }}" --password-stdin

    - name: Backend Image Build & Push
      run: |
        docker build -t ${{ secrets.DOCKER_USER }}/mhrs-backend:latest ./backend
        docker push ${{ secrets.DOCKER_USER }}/mhrs-backend:latest

    - name: Frontend Image Build & Push
      run: |
        docker build -t ${{ secrets.DOCKER_USER }}/mhrs-frontend:latest ./frontend
        docker push ${{ secrets.DOCKER_USER }}/mhrs-frontend:latest

    - name: Ansible kur
      run: sudo apt install ansible -y

    - name: SSH key ekle
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

    - name: Deploy
      run: ansible-playbook -i ansible/inventory.ini ansible/deploy.yml -e "docker_user=${{ secrets.DOCKER_USER }} docker_pass=${{ secrets.DOCKER_PASS }}"
      env:
        ANSIBLE_HOST_KEY_CHECKING: False
