name: CI-CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:

    - name: Repo çek
      uses: actions/checkout@v3

    # (Docker imajları sunucuda docker-compose ile derleneceği için bu adımlar kaldırıldı)

    - name: Ansible kur
      run: sudo apt install ansible -y

    - name: SSH key ekle
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

    - name: Deploy
      run: ansible-playbook -i ansible/inventory.ini ansible/deploy.yml -e "docker_user=${{ secrets.DOCKER_USER }}"
      env:
        ANSIBLE_HOST_KEY_CHECKING: False
